const products = [
    {
      id: "rec43w3ipXvP28vog",
      title: "high-back bench",
      company: "ikea",
      image: "C:\Users\Admin\Desktop\sofaset\Media\Images\product-1.jpeg",
      price: 9.99,
    },
    {
      id: "rec4f2RIftFCb7aHh",
      title: "albany table",
      company: "marcos",
      image: "Media/Images/product-2.jpeg",
      price: 79.99,
    },
    {
      id: "rec8kkCmSiMkbkiko",
      title: "accent chair",
      company: "caressa",
      image: "Media/Images/product-3.jpeg",
      price: 25.99,
    },
    {
      id: "recBohCqQsot4Q4II",
      title: "wooden table",
      company: "ikea",
      image: "Media/Images/product-4.jpeg",
  
      price: 45.99,
    },
    {
      id: "recDG1JRZnbpRHpoy",
      title: "dining table",
      company: "caressa",
      image: "Media/Images/product-5.jpeg",
  
      price: 6.99,
    },
    {
      id: "recNWGyP7kjFhSqw3",
      title: "sofa set",
      company: "caressa",
      image: "Media/Images/product-6.jpeg",
      price: 69.99,
    },
    {
      id: "recZEougL5bbY4AEx",
      title: "modern bookshelf",
      company: "liddy",
      image: "Media/Images/product-7.jpeg",
      price: 8.99,
    },
    {
      id: "recjMK1jgTb2ld7sv",
      title: "emperor bed",
      company: "liddy",
      image: "Media/Images/product-8.jpeg",
      price: 21.99,
    },
    {
      id: "recmg2a1ctaEJNZhu",
      title: "utopia sofa",
      company: "marcos",
      image: "Media/Images/product-9.jpeg",
      price: 39.95,
    },
    {
      id: "recvKMNR3YFw0bEt3",
      title: "entertainment center",
      company: "ikea",
      image: "Media/Images/product-10.jpeg",
      price: 29.98,
    },
    {
      id: "recxaXFy5IW539sgM",
      title: "albany sectional",
      company: "ikea",
      image: "Media/Images/product-11.jpeg",
      price: 10.99,
    },
    {
      id: "recyqtRglGNGtO4Q5",
      title: "leather sofa",
      company: "caressa",
      image: "Media/Images/product-12.jpeg",
      price: 9.99,
    },
  ];